routes/web.php
<?php

use App\Http\Controllers\FrontendController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');
require __DIR__.'/auth.php';


// Application routes
Route::resource('categories', App\Http\Controllers\CategoriesController::class)->middleware('auth');
Route::resource('tags', App\Http\Controllers\TagsController::class)->middleware('auth');
Route::resource('posts', App\Http\Controllers\PostsController::class)->middleware('auth');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTagRequest;
use App\Http\Requests\UpdateTagRequest;
use App\Models\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        Tag::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'Tag created successfully!');

        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.edit',compact(['tag']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $tag->update(['name' => $request->name]);
        $tag->save();

        session()->flash('success','Tag updated successfully!');
        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        session()->flash('success','Tag deleted successfully!');
        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.admin-panel.app')

@section('content')

<div class="card">
    <div class="card-header">
        <h2>Add new Tag</h2>
    </div>
    <div class="card-body">
        <form action="{{ route('tags.store')}}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text"
                       class="form-control @error('name')
                           is-invalid
                       @enderror"
                       id="name"
                       name="name"
                       value="{{ old('name')}}"
                       placeholder="Enter Tag Name:">
                @error('name')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>
            <button type="submit"
                    class="btn btn-outline-success">Submit</button>
        </form>
    </div>
  </div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.admin-panel.app')

@section('content')

<div class="card">
    <div class="card-header">
        <h2>Edit Tag</h2>
    </div>
    <div class="card-body">
        <form action="{{ route('tags.update', $tag->id)}}" method="POST">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text"
                       class="form-control @error('name')
                           is-invalid
                       @enderror"
                       id="name"
                       name="name"
                       value="{{ $tag->name }}"
                       placeholder="Enter Tag Name:">
                @error('name')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>
            <button type="submit"
                    name="submit"
                    class="btn btn-outline-success"
                    value="update">Update</button>
        </form>
    </div>
  </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="d-flex justify-content-end mb-3">
    <a href="{{ route('tags.create') }}" class="btn btn-primary">Add Tag</a>
</div>
<div class="card">
    <div class="card-header"><h2>Tags</h2></div>
    <div class="card-body">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col"> Actions</th>
              </tr>
            </thead>
            <tbody>
              @foreach ( $tags as $tag)
              <tr>
                <td> {{ $tag->name }} </td>
                <td>
                    <a href="{{ route('tags.edit',$tag->id) }}" class="btn btn-warning">Edit</a>
                    <button type="button"
                            onclick="displayModal({{$tag->id}})"
                            class="btn btn-danger"
                            data-toggle="modal"
                            data-target="#exampleModal">
                        Delete
                      </button>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-5">
      {{-- {{ $categories->links('vendor.pagination.bootstrap-4') }} --}}
  </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Action Delete</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="deleteModalForm">
            @csrf
            @method('DELETE')
            <div class="modal-body">
                Are you sure, you want to delete the tag ?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Delete Tag</button>
              </div>
        </form>
      </div>
    </div>
  </div>
@endsection
@section('page-level-scripts')
<script>
    function displayModal(tagID){
        var url = "/tags/" + tagID;
        $("#deleteModalForm").attr('action',url)
    }
</script>
@endsection