routes/web.php
<?php

use App\Http\Controllers\FrontendController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');
require __DIR__.'/auth.php';


// Application routes
Route::resource('categories', App\Http\Controllers\CategoriesController::class)->middleware('auth');
Route::resource('tags', App\Http\Controllers\TagsController::class)->middleware('auth');
Route::resource('posts', App\Http\Controllers\PostsController::class)->middleware('auth');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable = ['name'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        // Validation is already done with Requets
        // Store
        Category::create([
            'name' => $request->name
        ]);
        session()->flash('success', 'Category created successfully!');
        // Return to index
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function edit(Category $category)
    {
        return view('categories.edit',compact(['category']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        $category->name = $request->name;
        // $category->update(['name' => $request->name]);
        $category->save();

        session()->flash('success','Category updated successfully!');
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        session()->flash('success','Category deleted successfully!');
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.admin-panel.app')

@section('content')

<div class="card">
    <div class="card-header">
        <h2>Add new Category</h2>
    </div>
    <div class="card-body">
        <form action="{{ route('categories.store')}}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text"
                       class="form-control @error('name')
                           is-invalid
                       @enderror"
                       id="name"
                       name="name"
                       value="{{ old('name')}}"
                       placeholder="Enter Category Name:">
                @error('name')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>
            <button type="submit"
                    class="btn btn-outline-success">Submit</button>
        </form>
    </div>
  </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.admin-panel.app')

@section('content')

<div class="card">
    <div class="card-header">
        <h2>Edit Category</h2>
    </div>
    <div class="card-body">
        <form action="{{ route('categories.update', $category->id)}}" method="POST">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text"
                       class="form-control @error('name')
                           is-invalid
                       @enderror"
                       id="name"
                       name="name"
                       value="{{ $category->name }}"
                       placeholder="Enter Category Name:">
                @error('name')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>
            <button type="submit"
                    name="submit"
                    class="btn btn-outline-success"
                    value="update">Update</button>
        </form>
    </div>
  </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="d-flex justify-content-end mb-3">
    <a href="{{ route('categories.create') }}" class="btn btn-primary">Add Category</a>
</div>
<div class="card">
    <div class="card-header"><h2>Categories</h2></div>
    <div class="card-body">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col"> Actions</th>
              </tr>
            </thead>
            <tbody>
              @foreach ( $categories as $category)
              <tr>
                <td> {{ $category->name }} </td>
                <td>
                    <a href="{{ route('categories.edit',$category->id) }}" class="btn btn-warning">Edit</a>
                    <button type="button" onclick="displayModal({{$category->id}})" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                        Delete
                      </button>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-5">
      {{-- {{ $categories->links('vendor.pagination.bootstrap-4') }} --}}
  </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Action Delete</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="deleteModalForm">
            @csrf
            @method('DELETE')
            <div class="modal-body">
                Are you sure, you want to delete the category ?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Delete Category</button>
              </div>
        </form>
      </div>
    </div>
  </div>
@endsection
@section('page-level-scripts')
<script>
    function displayModal(categoryID){
        var url = "/categories/" + categoryID;
        $("#deleteModalForm").attr('action',url)
    }
</script>
@endsection